version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer_api
    ports:
      - "3000:3000"
    env_file: 
      - .env
    depends_on:
      - database
    volumes:
      - .:/app

  database:
    image: postgres:15
    container_name: producer_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
